FROM gradle as build
WORKDIR /app
COPY . .
RUN gradle build -x test

FROM openjdk:17
WORKDIR /app
COPY --from=build /app/build/libs/*.jar /app/ms10-sec.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","ms10-sec.jar"]
