apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms10-security
  namespace: msten-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms10
  template:
    metadata:
      labels:
        app: ms10
    spec:
      containers:
        - name: ms10-security-container
          image: emn503/ms10-security:arm
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_CONNECTION_IP
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_CONNECTION_IP
            - name: DB_CONNECTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_CONNECTION_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ms10-security-svc
  namespace: msten-prod
  labels:
    app: ms10
spec:
  selector:
    app: ms10
  ports:
    - protocol: TCP
      port: 8080
      name: http
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice-ingress-msten-security
  namespace: msten-prod
spec:
  hosts:
  - "*"
  gateways:
  - ms10demo1-gateway
  http:
  - match:
    - uri:
        prefix: /login
    route:
      - destination:
          host: ms10-security-svc