apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-conf
  namespace: msten-sec
data:
  my.cnf: |
    [mysqld]
    bind-address = 0.0.0.0
    default-authentication-plugin=mysql_native_password
    skip-host-cache
    skip-name-resolve
    datadir=/var/lib/mysql
    socket=/var/run/mysqld/mysqld.sock
    secure-file-priv=/var/lib/mysql-files
    user=mysql

    pid-file=/var/run/mysqld/mysqld.pid
    [client]
    socket=/var/run/mysqld/mysqld.sock

    !includedir /etc/mysql/conf.d/
