apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: msten-sec
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms10
  template:
    metadata:
      labels:
        app: ms10
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-conf
              mountPath: /etc/my.cnf
              subPath: my.cnf
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-conf
          configMap:
            name: mysql-conf
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: msten-sec
  labels:
    app: ms10
spec:
  selector:
    app: ms10
  ports:
    - protocol: TCP
      port: 3306
      name: http-mysql
      targetPort: 3306
  type: ClusterIP
