apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sec-to-mysql-virtualservice
  namespace: msten-sec
spec:
  hosts:
    - "ms10-security-svc"
  http:
    - route:
        - destination:
            host: mysql-service.msten-sec.svc.cluster.local
