stages:
  - build
  - dockerize
  - deploy

build:
  stage: build
  image: gradle:jdk11-alpine
  script:
    - gradle build -x test
  artifacts:
    paths:
      - build/libs/*.jar
  only: 
    - main
      
dockerize:
  stage: dockerize
  image: docker:dind
  script:
    - cp /builds/$CI_PROJECT_PATH/build/libs/*.jar ./
    - docker build -t $CI_REGISTRY_USER/mstensec:$CI_PIPELINE_ID .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push $CI_REGISTRY_USER/mstensec:$CI_PIPELINE_ID
  only: 
    - main

deploy:
  stage: deploy
  image: docker:dind
  script:
    - apk update
    - 'which ssh-agent || ( apk add openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - 'sed -i "s|image: \"image:tag\"|image: \"$CI_REGISTRY_USER/mstensec:$CI_PIPELINE_ID\"|g" deployment.yaml'
    - ls -la
    - scp ./* $KUBEMASTER:$DFPATH
    - ssh $KUBEMASTER kubectl apply -f $DFPATH/deployment.yaml
  only: 
    - main
